services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
  test_postgres:
    container_name: test_postgres
    image: postgres:13
    restart: always
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_data
    volumes:
      - /tmp:/tmp
volumes:
  inventory-data:
