services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "5001:3000"
      links:
        - "database"
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
    volumes:
      - inventory-data:/var/lib/postgresql/data
    ports:
      - "9001:5432"
    expose:
      - "9001"
volumes:
  inventory-data:
